### ISSUE TITLE
Not an Issue, but a Mention, and a thank you....

### ISSUE THREAD

**Issue by StudioJunkyard** [stefangabos/Zebra_Image#1]
Hi, I just wanted to let you know that we use Zebra Image in Libr8, another CMS, and wanted to thank the developer's behind Zebra Image for all their hard work.
https://github.com/StudioJunkyard/Libr8

**Comment by EddieOne** [comment]
Also would like to say thank you. I'm glad to see I'm not the only one who thinks a great PHP class is better than a bunch of dependencies and auto-loaders.

**Comment by stefangabos** [comment]
Thank you guys!

**Comment by StudioJunkyard** [comment]
The CMS is now called LibreCMS, and still using Zebra Image, lol.
