### ISSUE TITLE
How to write multiple images?

### ISSUE THREAD

**Issue by pdctpa** [stefangabos/Zebra_Image#10]
how can I write multiple images like thumb, medium size, whole image, etc/.

**Comment by stefangabos** [comment]
```php
$img->source_path = 'path/to/original_image.ext';

// largest image
$img->target_path = 'path/to/large.ext';
$img->resize(1920, 0);

// medium, maybe
$img->target_path = 'path/to/medium.ext';
$img->resize(640, 0);

// thumbnail
$img->target_path = 'path/to/thumbnail.ext';
$img->resize(150, 75);

**Comment by pdctpa** [comment]
Thanks, when am using this kind, resize for medium or thumbnail does not crop properly.

For example:

$image = new Zebra_Image();
$img = '..path/image.png';
$thumb = '..path/thumb.png';

$image->source_path = $img;
list($width, $height) = getimagesize($img);
if($width > 800){
$awidth = "800";
} else {
$awidth = $width;
}
if($height > 2000){
$aheight = "2000";
} else {
$aheight = $height;
}
    $image->target_path = $img;
    $image->jpeg_quality = 60;
    $image->preserve_aspect_ratio = true;
    $image->enlarge_smaller_images = true;
    $image->preserve_time = true;

    if (!$image->resize($awidth, $aheight, ZEBRA_IMAGE_BOXED)) {
//error
    } else {
        echo 'Success!';
    }
$image->target_path = $thumb;
if (!$image->resize(300, 600, ZEBRA_IMAGE_CROP_TOPLEFT)) {
	//error
} else {
	echo 'Success!';
}

Image which am uploading is 1200w * 4000h
first it puts in a box with 800w * 2000h
and for thumb it takes the whole image and creates thumbnail with 300w * 600h as its not cropping. 

Is it may be am using preserve_aspect_ratio to true. hence this is the issue, right?

Or may be am trying to crop png/gif format other than jpg extension, is that could be the problem?

Hope you are understanding what am trying to say.

**Comment by stefangabos** [comment]
Yes, you have to unset the "preserve_aspect_ratio" for the second call, by setting it to false

**Comment by pdctpa** [comment]
No, even after the unset of "preserve_aspect_ratio", still the same.

**Comment by stefangabos** [comment]
I know it's been a year...

I've tested your code and seems to work as expected. 

Indeed, the thumbnail is made from the first image - the one with 2000x4000. If you want to be made out of the already resized image you'd have set the `source_path` to the newly created image first.
