### ISSUE TITLE
PHP Warning exif_read_data(): File not supported

### ISSUE THREAD

**Issue by Hoffi1** [stefangabos/Zebra_Image#11]
If auto_handle_exif_orientation is true one gets a warning if file is e.g. a GIF image. This is because only JPEG and TIFF are supported by exif_read_data().

This could be prevented by changing line 1349 from ```if ($this->auto_handle_exif_orientation)``` 
to ```if ($this->auto_handle_exif_orientation && ($this->source_type === IMAGETYPE_JPEG))``` 
(because TIFF is not supported by Zebra_Image)

**Comment by stefangabos** [comment]
Fixed. Thanks!
