### ISSUE TITLE
PHP message: PHP Warning: exif_read_data(phpM6q1lm): Illegal IFD size in inc/ZebraImage.php on line 1360, referer: url

### ISSUE THREAD

**Issue by untitled7** [stefangabos/Zebra_Image#15]
PHP message: PHP Warning: exif_read_data(phpM6q1lm): Illegal IFD size in inc/ZebraImage.php on line 1360, referer: url

**Comment by stefangabos** [comment]
I need the image that produced this error

**Comment by stefangabos** [comment]
Are you running PHP 5.6.x?
