### ISSUE TITLE
Cropped image black borders

### ISSUE THREAD

**Issue by skerbis** [stefangabos/Zebra_Image#18]
Is it possible to set the background color if the cropped result is outside the image? 
Now it gets a black border. 
I only see a definition in the resize method but not at the cropping.

**Comment by stefangabos** [comment]
You mean like if from an 100x100 image I would crop 50, 50, 150, 150?

**Comment by stefangabos** [comment]
i think the best way would be to have it transparent for images that support transparency and a user defined colour for JPEG

**Comment by skerbis** [comment]
That would be nice

**Comment by skerbis** [comment]
Look: 
From
<img width="1179" alt="Bildschirmfoto 2020-01-23 um 16 21 59" src="https://user-images.githubusercontent.com/791247/72997380-93444800-3dfc-11ea-9c62-55a679046ff0.png">

I get this:
![redaxo_1](https://user-images.githubusercontent.com/791247/72997401-9c351980-3dfc-11ea-8a14-6eeb910d266a.png)

**Comment by skerbis** [comment]
Because it's possible to set the cropping outside the picture, I get black bars.

**Comment by stefangabos** [comment]
yes, i understand. i'll try and work on it over the weekend

**Comment by skerbis** [comment]
I‘ll test it

**Comment by stefangabos** [comment]
I did a commit that should fix this issue. It will automatically use a transparent colour for transparent GIF and PNGs and black for non-transparent images. A custom colour can be also specified. I updated the [documentation](https://stefangabos.github.io/Zebra_Image/Zebra_Image/Zebra_Image.html#methodcrop). Please consider this work-in-progress. Thanks!

**Comment by skerbis** [comment]
Cool 👍 thx. I will test it today

**Comment by skerbis** [comment]
@stefangabos tested 👍 .. thank you

**Comment by stefangabos** [comment]
thank you for reporting and testing. i've created a [release](https://github.com/stefangabos/Zebra_Image/releases/tag/2.4.0) so you can now update via composer
