### ISSUE TITLE
Output Progressive / Interlaced JPG

### ISSUE THREAD

**Issue by tohizma** [stefangabos/Zebra_Image#20]
Need switch option to set JPEG output as progressive/interlaced in GD
Thank you

**Comment by stefangabos** [comment]
ok, i will add it in the coming days. thank you!

**Comment by stefangabos** [comment]
See [documentation](https://stefangabos.github.io/Zebra_Image/Zebra_Image/Zebra_Image.html#var$jpeg_interlace).
Let me know if it works

**Comment by tohizma** [comment]
Sorry for late report

It's works!

But there's warning in PHP 7.1.1 (XAMPP)

`Warning: preg_match() expects parameter 2 to be string, resource given in D:\xampp\htdocs\tesbed\Zebra_Image.php on line 1561`

Maybe unrelated to Interlace switch. Here this my test code:

`<?php

require 'Zebra_Image.php';

$image = new Zebra_Image();

$image->auto_handle_exif_orientation = false;

$image->source_path = 'img-source.jpg';
$image->target_path = 'output-interlace.jpg';

$image->jpeg_quality = 100;
$image->jpeg_interlace = true;

$image->preserve_aspect_ratio = true;
$image->enlarge_smaller_images = true;
$image->preserve_time = true;

if (!$image->resize(1000, 1000, ZEBRA_IMAGE_CROP_CENTER)) {

    // if there was an error, let's see what the error is about
    switch ($image->error) {

        case 1:
            echo 'Source file could not be found!';
            break;
        case 2:
            echo 'Source file is not readable!';
            break;
        case 3:
            echo 'Could not write target file!';
            break;
        case 4:
            echo 'Unsupported source file format!';
            break;
        case 5:
            echo 'Unsupported target file format!';
            break;
        case 6:
            echo 'GD library version does not support target file format!';
            break;
        case 7:
            echo 'GD library is not installed!';
            break;
        case 8:
            echo '"chmod" command is disabled via configuration!';
            break;
        case 9:
            echo '"exif_read_data" function is not available';
            break;

    }

// if no errors
} else echo 'Success!';

echo '<img src="output-interlace.jpg">';`

**Comment by stefangabos** [comment]
Should be fixed now

**Comment by tohizma** [comment]
Great it is fixed now.

Thank you very much!

**Comment by stefangabos** [comment]
Thank you for you feedback
