### ISSUE TITLE
WebP support?

### ISSUE THREAD

**Issue by Taapo** [stefangabos/Zebra_Image#21]
Is there any plan to support webp?

**Comment by stefangabos** [comment]
sure, sounds like a good idea, thanks for bringing this up!
i added it to my todo list and hopefully will get it done over the weekend

**Comment by Taapo** [comment]
Awesome - would be a great addition. Problem is that GD doesn't webp for versions of php older than 7 - how do you think you'd solve this?

**Comment by stefangabos** [comment]
easy - it would work only if the [imagewebp](https://www.php.net/manual/en/function.imagewebp.php) function is available, or trigger an error otherwise. or maybe a fallback to a different image type (but i don't think that would be of any help)

**Comment by Taapo** [comment]
nice, good call - looking forward to having this added! thanks for the responsiveness :)

**Comment by stefangabos** [comment]
i've added support for WEBP. see also the [webp_quality](https://stefangabos.github.io/Zebra_Image/Zebra_Image/Zebra_Image.html#var$webp_quality) property

**Comment by stefangabos** [comment]
not yet available as a release. please give it a spin and if it works i'll publish a new release. thanks!

**Comment by stefangabos** [comment]
this is now available as a [release](https://github.com/stefangabos/Zebra_Image/releases/tag/2.6.0)
