### ISSUE TITLE
Resize Mode Doesn't Work in PHP 8.1

### ISSUE THREAD

**Issue by tohizma** [stefangabos/Zebra_Image#23]
All resize mode except ZEBRA_IMAGE_BOXED and ZEBRA_IMAGE_NOT_BOXED and ZEBRA_IMAGE_CROP_TOPLEFT (obviously) doesn't work as intented, they all start cropping from top left just like ZEBRA_IMAGE_CROP_TOPLEFT 

using this test code in PHP 8.1 environment

```
<?php
require "Zebra_Image.php";

$mode = [ZEBRA_IMAGE_BOXED,
		ZEBRA_IMAGE_NOT_BOXED,
		ZEBRA_IMAGE_CROP_TOPLEFT,
		ZEBRA_IMAGE_CROP_TOPCENTER,
                ZEBRA_IMAGE_CROP_TOPRIGHT,
                ZEBRA_IMAGE_CROP_MIDDLELEFT,
                ZEBRA_IMAGE_CROP_CENTER,
                ZEBRA_IMAGE_CROP_MIDDLERIGHT,
                ZEBRA_IMAGE_CROP_BOTTOMLEFT,
                ZEBRA_IMAGE_CROP_BOTTOMCENTER,
                ZEBRA_IMAGE_CROP_BOTTOMRIGHT];
		
function saveImage($mode)
{
	$image = new Zebra_Image(); 
	$image->source_path = 'test.jpg';
	$image->target_path = 'test-thumb-'.$mode.'.jpg';
	$image->jpeg_quality = 60;
	$image->preserve_aspect_ratio = true;
	$image->enlarge_smaller_images = true;        
	$image->preserve_time = true;
	$image->handle_exif_orientation_tag = true;
	$image->sharpen = true;
	$image->jpeg_interlace = true;        
	$image->resize(200, 200, $mode);
        
	return $image->error;
}

echo '<img src="test.jpg" /><br />';
foreach ($mode as $m) {
	saveImage($m);	
        echo '<img src="test-thumb-'.$m.'.jpg" />';
}
?>
```

**Comment by stefangabos** [comment]
hmmm, it's not working in 7 neither...it might have to do with GD maybe...
i am looking into it now
thanks for reporting

**Comment by stefangabos** [comment]
i remember now! :)
this is the expected behavior. the library will try to resize the image first and if after resizing, while maintaining the aspect ratio, the image is not the desired width and height, cropping will be involved. 
therefore, resizing a square image to a square width/height will always be perfect and no cropping will be involved.
you will see the modes being used when resizing to something like 400x100 or anything that's not a square

**Comment by stefangabos** [comment]
...but there's another issue on PHP 8, see changelog for [imagecopyresampled](https://www.php.net/manual/en/function.imagecopyresampled.php). i am trying to fix that now

**Comment by tohizma** [comment]
i think the problem is in $target_identifier doesn't resized (shrunk) before cropping, if i replace $target_width and $target_height to $this->source_width and $this->source_height on crop parameter calculation in method switch, the rectangular area of cropped get right.

I've try with several image sources (rectangular, square, less dimension than target) has same result, probably gd change something internally on imagecopyresampled

**Comment by tohizma** [comment]
resize mode other than boxed doesn't shrunk original image, just bare crop in original image, with wrong calculated area of cropping

![image](https://user-images.githubusercontent.com/5330172/170860606-a6e99989-6ad3-40ec-b15a-70d011de11b9.png)

**Comment by stefangabos** [comment]
i pushed a fix earlier for PHP 8. please download from GitHub and try again

**Comment by stefangabos** [comment]
but it seems like you don't want resize but a crop

**Comment by tohizma** [comment]
Great! Now working just like in old gd and php

But you need explicitly cast to integer ```(int)``` for imagecopyresampled params (and for safety, any other function params which expect integer), PHP 8.1 strict always pop up warning

```
NOTICE: PHP message: PHP Deprecated:  Implicit conversion from float 12.5 to int loses precision in /var/www/html/tesdev/html/Zebra_Image.php on line 1156
```

I just need make thumbnail and crop from specific area of interest to create fixed size thumbnail, now it is working great, except minor warning above,  thank you

**Comment by stefangabos** [comment]
Can you please show me an example of how to get to a warning like that?

**Comment by stefangabos** [comment]
ah, got it - by not using integer width/height. ok

**Comment by stefangabos** [comment]
Should be fixed now

**Comment by stefangabos** [comment]
I published a new release so it is now also available via Composer
Thanks a lot for reporting and for the feedback!
