### ISSUE TITLE
Animated WEBP images throw exception

### ISSUE THREAD

**Issue by yani** [stefangabos/Zebra_Image#25]
`Zebra_image.php:1523 imagecreatefromwebp()` fails when loading an animated webp image.
It throws this exception: `ErrorException: gd-webp cannot allocate temporary buffer`

It has nothing to do with any buffer. It just seems to be not implemented into **libgd** at the moment.

Maybe a fix is to add a ZebraImage error saying that libgd does not currently support this?

This seems to be a good function to check if a webp image is animated:
https://stackoverflow.com/a/61242086

Sources:
https://github.com/libgd/libgd/issues/648
https://bugs.php.net/bug.php?id=79809&thanks=4
https://www.php.net/manual/en/function.imagecreatefromwebp.php

I might pick this up myself but wanted to create the issue first.

**Comment by stefangabos** [comment]
thanks for the heads-up!
i'll work on the fix today and let you know

**Comment by stefangabos** [comment]
It needs some testing in the real world. Once that's done I'll publish a new release
