### ISSUE TITLE
php 8.1.12 - imagecolorsforindex Argument #2 ($color) is out of range

### ISSUE THREAD

**Issue by mce1978** [stefangabos/Zebra_Image#26]
Zebra version:	"stefangabos/zebra_image": "^2.8"
PHP Version 8.1.12
GD Version | bundled (2.1.0 compatible)

Zebra_Image stops executing on some gif images on my site. It fails hard so I have to add a try catch around the Zebra code. No image is generated.

The error is: imagecolorsforindex Argument #2 ($color) is out of range 
Line: 1491

`$this->source_transparent_color = @imagecolorsforindex($identifier, $this->source_transparent_color_index);`

Seems like source_transparent_color_index is greater than the total number of colors in the image.

Similiar errors and solutions:
[Stackoverflow](https://stackoverflow.com/questions/3874533/what-could-cause-a-color-index-out-of-range-error-for-imagecolorsforindex/3898007#3898007)
[ProcessWire](https://github.com/processwire/processwire-issues/issues/1299)

If I change line 1491 to this it works.

`                        if ($this->source_transparent_color_index <= imagecolorstotal($identifier)) {
                            $this->source_transparent_color = @imagecolorsforindex($identifier, $this->source_transparent_color_index);
                        }
`

Example gif:
![300x300-nophoto](https://user-images.githubusercontent.com/1219602/209928997-5fd2cbc5-0f23-40cf-b48a-fa2274f651d9.gif)

**Comment by stefangabos** [comment]
Thanks for the heads-up! Should be fixed now

**Comment by mce1978** [comment]
Thanks, the fix works fine! When do you make the next release?

**Comment by stefangabos** [comment]
Done. 
Thanks again!
