### ISSUE TITLE
error deprecated with php7

### ISSUE THREAD

**Issue by jojo12** [stefangabos/Zebra_Image#6]
#Hi,
I tried with php 7 on Joomla! 3.5 and got an error.
Do you know and will there be an update?
The use of Zebra_Image is a part in JEM -Joomlaeventmanager. And I like it.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Zebra_Image has a deprecated constructor in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/Zebra_Image.php on line 46

**Comment by geekwright** [comment]
Scared me, because my PHP7 testing didn't catch this, but that is because it was fixed quite some time ago. The current version 2.2.4 does not have that issue.
