### ISSUE TITLE
Where are the definitions for IMG_FILTER_*

### ISSUE THREAD

**Issue by reyco1** [stefangabos/Zebra_Image#7]
I can't apply any filters because the filters are not defined anywhere. It aways throws an error because the filters are not defined anywhere in the file. Can't find IMG_FILTER_GAUSIAN_BLUR... Was the filter functionality removed?

**Comment by geekwright** [comment]
Those are defined by the GD extension: http://php.net/manual/en/function.imagefilter.php

**Comment by stefangabos** [comment]
Thanks
