### ISSUE TITLE
resized png's do not retain alpha

### ISSUE THREAD

**Issue by audas** [stefangabos/Zebra_Image#9]
resizing a png image with an alpha background does not preserve transparency ?
![577320da52881](https://cloud.githubusercontent.com/assets/274994/16437530/1fffa250-3deb-11e6-84a5-bd193ac67020.png)

I am trying to overlay this in FFMPEG - it may well be that it requires png colortype=6 ?

**Comment by stefangabos** [comment]
I can't confirm this. I used the image provided with the included example and it resized it fine.

**Comment by stefangabos** [comment]
I think the issue was solved by fc8d697
